# Generated by Django 2.1.7 on 2019-03-20 22:25

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_auto_20190319_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoples',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='peoples',
            name='mobile',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='موبایل'),
        ),
        migrations.AlterField(
            model_name='peoples',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='peoples',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='peoples',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
